# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachables', '0003_auto_20170815_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=140)),
                ('intro', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachables.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='step',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Subtopic',
        ),
        migrations.AddField(
            model_name='step',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachables.Lesson'),
        ),
    ]
