# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachables', '0004_auto_20170816_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.ImageField(default='placeholder.png', upload_to='user_uploaded/%Y/%m/'),
        ),
    ]
