# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachables', '0005_step_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(default='placeholder.png', upload_to='user_uploaded/'),
        ),
    ]
